nosana:
  description: Nosana

global:
  image: alpine:latest

  trigger:
    branch:
      - "*"

jobs:
  - name: build
    commands:
      - npm ci
      - npm run build:program-rust
    artifacts:
      - name: node_modules
      - name: dist

  - name: test
    commands:
      - npm run test:program-rust
    resources:
      - name: node_modules
      - name: dist